name: Deploy blog to Pages

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.235.0
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 2 # Increment this number if you need to re-download cached gems
          bundler: 2.1.4
          rubygems: 3.4.6
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Install Java+PlantUML+libvips-tools (for image compression)
        run: |
          sudo apt-get update
          # From https://github.com/metanorma/plantuml-install/blob/main/ubuntu.sh
          sudo apt-get install -y default-jre graphviz libvips-tools
          PLANTUML_URL="https://github.com/plantuml/plantuml/releases/download/v1.2024.4/plantuml-1.2024.4.jar"
          mkdir -p /opt/plantuml
          curl -o /opt/plantuml/plantuml.jar -L "${PLANTUML_URL}"
          printf '#!/bin/sh\nexec java -Djava.awt.headless=true -jar /opt/plantuml/plantuml.jar "$@"' | sudo tee /usr/bin/plantuml
          sudo chmod +x /usr/bin/plantuml
          
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    concurrency:
        group: "pages"
        cancel-in-progress: true
    if: github.ref == 'refs/heads/master' || (github.event.action == 'closed' && github.event.pull_request.merged == true)
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
